driver:
  name: vagrant
  require_chef_omnibus: '12.5.1'
  customize:
    memory: 1024

provisioner:
  name: chef_zero
  attributes:
    ibm-im-test:
      passport_advantage:
        user: <%= ENV['PASSPORTADV_USER'] %>
        password: <%= ENV['PASSPORTADV_PW'] %>
        
platforms:
  - name: centos-6.7

suites:
  - name: install_im
    run_list:
    - recipe[ibm-im-test::install_im]
  - name: install_passport
    run_list:
    - recipe[ibm-im-test::install_passport]
