driver:
  name: dokken
  require_chef_omnibus: latest
  privileged: true # because Docker and SystemD/Upstart

verifier:
  root_path: '/opt/verifier'
  sudo: false

transport:
  name: dokken

provisioner:
  name: dokken
  attributes:
    ibm-im-test:
      passport_advantage:
        user: <%= ENV['PASSPORTADV_USER'] %>
        password: <%= ENV['PASSPORTADV_PW'] %>

platforms:
- name: centos-6
  driver:
    image: centos:6
- name: centos-7
  driver:
    image: centos:7
- name: ubuntu-12.04
  driver:
    image: ubuntu-upstart:12.04
- name: ubuntu-14.04
  driver:
    image: ubuntu-upstart:14.04

suites:
  - name: install_im
    run_list:
    - recipe[ibm-im-test::install_im]
  - name: install_passport
    run_list:
    - recipe[ibm-im-test::install_passport]
