driver:
  name: vagrant
  require_chef_omnibus: '12.5.1'
  customize:
    memory: 1024

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7

suites:
  - name: im_install
    run_list:
    - recipe[ibm-im-test::install_im]
  - name: was_install
    run_list:
    - recipe[ibm-im-test::install_was]
  - name: was_install_response
    run_list:
    - recipe[ibm-im-test::install_was_response]
