# # Rubocop,  we're buddies and all,  but we're going to have to disagree on the following -
#
# # Increase line length, we're not on VT220s anymore
LineLength:
  Max: 180

##  don't need class documentation header for custom resources.
Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': []
    '%I': []
    '%w': []
    '%W': []
    '%i': '[]'
    '%I': '[]'
    '%w': '[]'
    '%W': '[]'

